### ISSUE TITLE
no language in app(russian in may project)

### ISSUE THREAD

**Issue by lightarhont** [fabiocaccamo/django-redirects#1]
**Python version**
3.7

**Django version**
3.1

**Package version**
0.1.0

**Current behavior (bug description)**

**Expected behavior**

**Comment by fabiocaccamo** [comment]
@lightarhont I close this issue since it's not my intention to localize this library, if you do it feel free to submit a PR.

**Comment by fabiocaccamo** [comment]
@lightarhont I created russian localization .po file for you: https://github.com/fabiocaccamo/django-redirects/blob/main/redirects/locale/ru/LC_MESSAGES/django.po 

If you submit a PR with translations I will merge it.
