### ISSUE TITLE
Redirect is not deleted, when deleting from the base

### ISSUE THREAD

**Issue by lightarhont** [fabiocaccamo/django-redirects#3]
**Python version**
3.8

**Django version**
3.1

**Package version**
git+https://github.com/lightarhont/django-redirects

**Current behavior (bug description)**
I`m add import export ability to package. But if i`m remove redirect from database, redirect worked. I`m clear cache, иut the error remains.

**Expected behavior**
When removing the redirect must stop working

**Comment by fabiocaccamo** [comment]
@lightarhont thank you for reporting this. 

`django-redirects` doesn't use cache at all, it does 1 query for each request, so this error sounds to me like a browser caching issue. 

Could you try to test the redirect (after deletion) using another browser (or private window), please?

**Comment by lightarhont** [comment]
Hmm, in cromium worked. Thanks!26.05.2021, 17:26, "Fabio Caccamo" ***@***.***>:
@lightarhont thank you for reporting this.
django-redirects doesn't use cache at all, it does 1 query for each request, so this error sounds to me like a browser caching issue.
Could you try to test the redirect (after deletion) using another browser (or private window), please?
